# Generated by Django 3.2.12 on 2022-02-22 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_initial_services(apps, schema_editor):
 
    Service = apps.get_model("service", "Service")
    # Microsoft test services
    Service.objects.create(description="Skype")
    Service.objects.create(description="OneDrive")
    Service.objects.create(description="Teams")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iris_token', models.CharField(db_index=True, max_length=64, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.RunPython(create_initial_services),
    ]
