Class djangointerop.bo.RequestServiceAccessRequest Extends Ens.StringContainer
{

Property service [ InitialExpression = "Teams" ];

Storage Default
{
<Data name="RequestServiceAccessRequestDefaultData">
<Subscript>"RequestServiceAccessRequest"</Subscript>
<Value name="1">
<Value>service</Value>
</Value>
</Data>
<DefaultData>RequestServiceAccessRequestDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
